name: circuit_breaker
description: A library for async retry, circuit breaker, request hedging, and adaptive throttling.
version: 0.1.0

environment:
  sdk: '>=3.11.0-0 <4.0.0'

dev_dependencies:
  test: ^1.24.0
